// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type MicrosegAlpnKey struct {
	_        structs.HostLayout
	CgroupId uint64
	Hash     uint64
}

type MicrosegDefaultCfg struct {
	_                     structs.HostLayout
	DefaultEgressVerdict  uint8
	DefaultIngressVerdict uint8
	EmitAllowEvents       uint8
	BlockQuic             uint8
	NumTlsPorts           uint8
	Pad                   [3]uint8
	TlsPorts              [8]uint16
	SampleRate            uint32
}

type MicrosegDnsNameBuf struct {
	_    structs.HostLayout
	Name [64]uint8
}

type MicrosegFlowEvent struct {
	_          structs.HostLayout
	TsNs       uint64
	CgroupId   uint64
	Family     uint8
	Direction  uint8
	Verdict    uint8
	Protocol   uint8
	SrcPort    uint16
	DstPort    uint16
	PolicyId   uint32
	SrcIp      [16]uint8
	DstIp      [16]uint8
	DropReason uint8
	L7DnsName  [64]uint8
	_          [3]byte
}

type MicrosegLpmV4Key struct {
	_         structs.HostLayout
	PrefixLen uint32
	CgroupId  uint64
	PeerPort  uint16
	Protocol  uint8
	Ip        [4]uint8
}

type MicrosegLpmV6Key struct {
	_         structs.HostLayout
	PrefixLen uint32
	CgroupId  uint64
	PeerPort  uint16
	Protocol  uint8
	Ip        [16]uint8
}

type MicrosegPolicyValue struct {
	_        structs.HostLayout
	Verdict  uint8
	Pad      [3]uint8
	PolicyId uint32
}

type MicrosegSniLpmKey struct {
	_         structs.HostLayout
	PrefixLen uint32
	CgroupId  uint64
	Name      [128]uint8
}

// LoadMicroseg returns the embedded CollectionSpec for Microseg.
func LoadMicroseg() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_MicrosegBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Microseg: %w", err)
	}

	return spec, err
}

// LoadMicrosegObjects loads Microseg and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*MicrosegObjects
//	*MicrosegPrograms
//	*MicrosegMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadMicrosegObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadMicroseg()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// MicrosegSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type MicrosegSpecs struct {
	MicrosegProgramSpecs
	MicrosegMapSpecs
	MicrosegVariableSpecs
}

// MicrosegProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type MicrosegProgramSpecs struct {
	MicrosegEgress  *ebpf.ProgramSpec `ebpf:"microseg_egress"`
	MicrosegIngress *ebpf.ProgramSpec `ebpf:"microseg_ingress"`
}

// MicrosegMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type MicrosegMapSpecs struct {
	DnsScratch    *ebpf.MapSpec `ebpf:"dns_scratch"`
	DroppedEvents *ebpf.MapSpec `ebpf:"dropped_events"`
	EgressV4      *ebpf.MapSpec `ebpf:"egress_v4"`
	EgressV6      *ebpf.MapSpec `ebpf:"egress_v6"`
	Events        *ebpf.MapSpec `ebpf:"events"`
	IngressV4     *ebpf.MapSpec `ebpf:"ingress_v4"`
	IngressV6     *ebpf.MapSpec `ebpf:"ingress_v6"`
	MicrosegCfg   *ebpf.MapSpec `ebpf:"microseg_cfg"`
	SniScratch    *ebpf.MapSpec `ebpf:"sni_scratch"`
	TlsAlpnDeny   *ebpf.MapSpec `ebpf:"tls_alpn_deny"`
	TlsSniLpm     *ebpf.MapSpec `ebpf:"tls_sni_lpm"`
}

// MicrosegVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type MicrosegVariableSpecs struct {
	UnusedFlowEvent *ebpf.VariableSpec `ebpf:"unused_flow_event"`
	UnusedSni       *ebpf.VariableSpec `ebpf:"unused_sni"`
	UnusedV4        *ebpf.VariableSpec `ebpf:"unused_v4"`
	UnusedV6        *ebpf.VariableSpec `ebpf:"unused_v6"`
}

// MicrosegObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadMicrosegObjects or ebpf.CollectionSpec.LoadAndAssign.
type MicrosegObjects struct {
	MicrosegPrograms
	MicrosegMaps
	MicrosegVariables
}

func (o *MicrosegObjects) Close() error {
	return _MicrosegClose(
		&o.MicrosegPrograms,
		&o.MicrosegMaps,
	)
}

// MicrosegMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadMicrosegObjects or ebpf.CollectionSpec.LoadAndAssign.
type MicrosegMaps struct {
	DnsScratch    *ebpf.Map `ebpf:"dns_scratch"`
	DroppedEvents *ebpf.Map `ebpf:"dropped_events"`
	EgressV4      *ebpf.Map `ebpf:"egress_v4"`
	EgressV6      *ebpf.Map `ebpf:"egress_v6"`
	Events        *ebpf.Map `ebpf:"events"`
	IngressV4     *ebpf.Map `ebpf:"ingress_v4"`
	IngressV6     *ebpf.Map `ebpf:"ingress_v6"`
	MicrosegCfg   *ebpf.Map `ebpf:"microseg_cfg"`
	SniScratch    *ebpf.Map `ebpf:"sni_scratch"`
	TlsAlpnDeny   *ebpf.Map `ebpf:"tls_alpn_deny"`
	TlsSniLpm     *ebpf.Map `ebpf:"tls_sni_lpm"`
}

func (m *MicrosegMaps) Close() error {
	return _MicrosegClose(
		m.DnsScratch,
		m.DroppedEvents,
		m.EgressV4,
		m.EgressV6,
		m.Events,
		m.IngressV4,
		m.IngressV6,
		m.MicrosegCfg,
		m.SniScratch,
		m.TlsAlpnDeny,
		m.TlsSniLpm,
	)
}

// MicrosegVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadMicrosegObjects or ebpf.CollectionSpec.LoadAndAssign.
type MicrosegVariables struct {
	UnusedFlowEvent *ebpf.Variable `ebpf:"unused_flow_event"`
	UnusedSni       *ebpf.Variable `ebpf:"unused_sni"`
	UnusedV4        *ebpf.Variable `ebpf:"unused_v4"`
	UnusedV6        *ebpf.Variable `ebpf:"unused_v6"`
}

// MicrosegPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadMicrosegObjects or ebpf.CollectionSpec.LoadAndAssign.
type MicrosegPrograms struct {
	MicrosegEgress  *ebpf.Program `ebpf:"microseg_egress"`
	MicrosegIngress *ebpf.Program `ebpf:"microseg_ingress"`
}

func (p *MicrosegPrograms) Close() error {
	return _MicrosegClose(
		p.MicrosegEgress,
		p.MicrosegIngress,
	)
}

func _MicrosegClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed microseg_bpfel.o
var _MicrosegBytes []byte
